name: Test
on:
  pull_request:
    branches:
      - master

# To run CI against unrelased go-ipfs or js-ipfs-* code (eg. wip PR),
# uncomment env below and define git revisions in ./scripts/custom-runtime.sh

env:
  IPFS_GO_EXEC: /tmp/go-ipfs/cmd/ipfs/ipfs
  IPFS_JS_EXEC: /tmp/js-ipfs/packages/ipfs/src/cli.js
  IPFS_JS_MODULE: /tmp/js-ipfs/packages/ipfs/dist/cjs/src/index.js
  IPFS_JS_HTTP_MODULE: /tmp/js-ipfs/packages/ipfs-http-client/dist/cjs/src/index.js

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            /tmp/*-ipfs/**
            ./go-libp2p-relay-daemon
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        run: |
            npm install
            ./scripts/custom-runtime.sh
            npm run build

  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            /tmp/*-ipfs/**
            ./go-libp2p-relay-daemon
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: |
          npm run lint
          npm run dep-check

  test-node:
    needs: build
    runs-on: ubuntu-latest
    name: test node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            /tmp/*-ipfs/**
            ./go-libp2p-relay-daemon
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test -- -t node

  test-browser:
    needs: build
    runs-on: ubuntu-latest
    name: test ${{ matrix.browser }} ${{ matrix.type }}
    strategy:
      matrix:
        browser:
          - chromium
          - firefox
        type:
          - browser
          - webworker
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            /tmp/*-ipfs/**
            ./go-libp2p-relay-daemon
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test -- -t ${{ matrix.type }} -- --browser ${{ matrix.browser }}

  test-electron:
    needs: check
    runs-on: ubuntu-latest
    name: test ${{ matrix.type }}
    strategy:
      matrix:
        type:
          - electron-main
          - electron-renderer
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            /tmp/*-ipfs/**
            ./go-libp2p-relay-daemon
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test -- -t ${{ matrix.type }} --bail -f dist/cjs/node-test/*js
