name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# To run CI against unrelased go-ipfs or js-ipfs-* code (eg. wip PR),
# uncomment env below and define git revisions in ./scripts/custom-runtime.sh

#env:
  #IPFS_GO_EXEC: /tmp/go-ipfs/cmd/ipfs/ipfs
  #IPFS_JS_EXEC: /tmp/js-ipfs/packages/ipfs/src/cli.js
  #IPFS_JS_MODULE: /tmp/js-ipfs/packages/ipfs/dist/cjs/src/index.js
  #IPFS_JS_HTTP_MODULE: /tmp/js-ipfs/packages/ipfs-http-client/dist/cjs/src/index.js

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh

  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh
      - run: |
          npm run lint
          npm run dep-check

  test-node:
    needs: build
    runs-on: ubuntu-latest
    name: test node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh
      - run: npm run test -- -t node

  test-browser:
    needs: build
    runs-on: ubuntu-latest
    name: test ${{ matrix.browser }} ${{ matrix.type }}
    strategy:
      matrix:
        browser:
          - chromium
          - firefox
        type:
          - browser
          - webworker
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh
      - run: npm run test -- -t ${{ matrix.type }} -- --browser ${{ matrix.browser }}

  test-electron:
    needs: check
    runs-on: ubuntu-latest
    name: test ${{ matrix.type }}
    strategy:
      matrix:
        type:
          - electron-main
          - electron-renderer
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test -- -t ${{ matrix.type }} --bail -f dist/cjs/node-test/*js

  release:
    # needs: [test-node, test-browser, test-electron]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            /tmp/*-ipfs/**
            ./scripts/libp2p-relay-daemon
          build: |
            ./scripts/custom-runtime.sh
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - run: npm run --if-present release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
